### ISSUE TITLE
Performance optimization for basic backtesting

### ISSUE THREAD

**Issue by multidis** [JuliaQuant/TradingLogic.jl#16]
Current [goldencross test](https://github.com/JuliaQuant/TradingLogic.jl/blob/master/test/teststrategy_goldencross.jl) run is slow. Need to optimize how OHLC signal updates take place and related processes such as SMA calculation.

**Comment by multidis** [comment]
[QuantProfiling](https://github.com/multidis/QuantProfiling.jl) based summary of performance optimization aspects:
- OHLC signal updates with [TimeArray chunks](https://github.com/multidis/QuantProfiling.jl/blob/master/src/Reactive_push_lift_ohlc/ohlc_updates_timearray.jl) are very inefficient: this appears to be the most limiting aspect in the current implementation. **Pushing row-vectors** as `timearray.values[i,:]` to the OHLC-signal [improves performance](https://github.com/multidis/QuantProfiling.jl/blob/master/src/Reactive_push_lift_ohlc/ohlc_updates_vector_tavalues.jl#L27) by almost an order of magnitude.
- For timestamped OHLC signals, pushing `timearray[i]` is [not efficient](https://github.com/multidis/QuantProfiling.jl/blob/master/src/Reactive_push_lift_ohlc/ohlc_updates_tarow.jl). Using a tuple `(DateTime, row-vector)` is [better](https://github.com/multidis/QuantProfiling.jl/blob/master/src/Reactive_push_lift_ohlc/ohlc_updates_vector_tavaluesvec_tstamp.jl).
- **Avoid multiple lift-signals** as much as possible: each separate lift adds time (e.g. [2 lift-signals](https://github.com/multidis/QuantProfiling.jl/blob/master/src/Reactive_push_lift_ohlc/ohlc_updates_morelift.jl#L28) vs. [1 lift-signal](https://github.com/multidis/QuantProfiling.jl/blob/master/src/Reactive_push_lift_ohlc/ohlc_updates_onelift.jl#L27)) and memory allocation to signal updates. Instead, try [unifying](https://github.com/multidis/QuantProfiling.jl/blob/master/src/Reactive_push_lift_ohlc/ohlc_updates_comblift.jl#L9) and/or **using values of [existing](https://github.com/multidis/QuantProfiling.jl/blob/master/src/Reactive_push_lift_ohlc/ohlc_updates_nomorelift.jl#L18) signals - PREFERABLE**. NOTE: fine to call `signal.value` multiple times, generally no need to pre-copy it to a separate variable.
- SMA calculation with TimeArray chunks is [slow](https://github.com/multidis/QuantProfiling.jl/blob/master/src/Reactive_sma/sma_stream_timearray.jl#L29). Using OHLC row-vector signal updates with a [foldl-based value buffer](https://github.com/multidis/QuantProfiling.jl/blob/master/src/Reactive_sma/sma_stream_buffervec.jl#L16) with SMA-length is much more efficient. Use **push-shift value buffer** for reactive updates that require signal history. NOTE: [recursive implementation](https://github.com/multidis/QuantProfiling.jl/blob/master/src/Reactive_sma/sma_stream_buffervec_recur.jl#L15) for SMA is less efficient.

**Comment by milktrader** [comment]
Thanks for doing this! I'll keep tabs on the progress.

**Comment by multidis** [comment]
Reasonable speedup achieved after some signal restructuring
https://github.com/JuliaQuant/TradingLogic.jl/commit/c82d0c4f3b66e39d36ded915435639037dad6056
