### ISSUE TITLE
add project to Projects using Docile / Lexicon

### ISSUE THREAD

**Issue by peter1000** [JuliaQuant/TradingLogic.jl#17]
hi,

I saw your issue on Lexicon issue list.
I would like to add your project to [Projects using Docile / Lexicon](https://github.com/MichaelHatherly/Docile.jl#projects-using-docile--lexicon)
if that is fine with you.

Thanks.

**Comment by multidis** [comment]
Thanks for pointing out. PR submitted:
https://github.com/MichaelHatherly/Docile.jl/pull/126
