### ISSUE TITLE
Upgrade to 1.0

### ISSUE THREAD

**Issue by alexandrebrilhante** [JuliaQuant/TradingLogic.jl#22]
Opening this issue as a reminder to upgrade to 1.0 (first to 0.7). To be done conjointly with `JuliaQuant/Reactive.jl`.

**Comment by multidis** [comment]
PR is welcomed!

**Comment by bicepjai** [comment]
Is this package active ?

**Comment by multidis** [comment]
This package relies on [Reactive.jl](https://github.com/JuliaGizmos/Reactive.jl), which has not been supported/updated for a while. There are some plans on updating the package to Julia 1 but no ETA yet as it requires a replacement for Reactive (fairly invasive in terms of the code). A relatively new [Rocket.jl](https://github.com/biaslab/Rocket.jl) package is one alternative under consideration.
