### ISSUE TITLE
Scaffold testing framework

### ISSUE THREAD

**Issue by milktrader** [JuliaQuant/TradingLogic.jl#6]
Recommending the standardized Julia `FactCheck` package here. 

I'll be happy to assign this to myself if you'd like @multidis

**Comment by multidis** [comment]
Indeed `FactCheck` is what is being used, it was just that initial commit with Base test placeholder file.

**Comment by milktrader** [comment]
Nice work. Package evaluator will read a REQUIRE file in `test/` that should include at least the `FactCheck` package (and later on `MarketData` of there are data sets there that you may use).

Looks great so far.

**Comment by multidis** [comment]
Included REQUIRE in `test/` along with test completion commit. Thanks.
