### ISSUE TITLE
Scaffold read the docs

### ISSUE THREAD

**Issue by milktrader** [JuliaQuant/TradingLogic.jl#7]
Another standardized documentation system for the package which I'm happy to assign to myself @multidis

**Comment by multidis** [comment]
Would be great @milktrader if not too much trouble while you are doing readthedocs for other packages. With such a doc system we'll have a place to add info as the development progresses.

A link could also be made to the [API doc](https://github.com/JuliaQuant/TradingLogic.jl/blob/master/docs/api.md) generated by `Lexicon.jl`, such as [this one](https://michaelhatherly.github.io/Docile.jl/index.html#module-api).

**Comment by milktrader** [comment]
Busy of late but I'll get this up soon!
